version: '1'
services:
  model:
    container_name: model-container
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODELS=./data/ollama/models
  application:
    container_name: application-container
    image: application
    ports:
      - 8501:8501


