version: '1'
services:
  model:
    container_name: model-container
    image: tgi
    volumes:
      - ./data:/data
    ports:
      - 80:80
    environment:
      # - HUGGINGFACE_OFFLINE=1
      - HUGGINGFACE_TOKEN=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
    shm_size: '1gb'
    command: ["--model-id", "bigscience/mt0-small", "--disable-custom-kernels", "--trust-remote-code"]
  application:
    container_name: application-container
    image: application
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    ports:
      - 7860:7860
  
volumes:
  data:
