version: '1'
services:
  ollama-container:
    image: ollamav2
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_MODELS=./data/ollama/models
  streamlit-app:
    image: streamv4
    ports:
      - 8501:8501


